
clustering {
  ip = "127.0.0.1"
  cluster.name = jtrack
  masterport = "2558"
  masternode = "127.0.0.1"
}

squbs {
  actorsystem-name = ${clustering.cluster.name}
}

default-listener{
  bind-port = 8085
}

kamon.util.filters {
  "akka.tracked-actor" {
    includes = [ "**" ]
  }
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"

  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = ${clustering.ip}
      port = 2558
    }
  }

  actor {
    provider = "akka.cluster.ClusterActorRefProvider"
  }

  cluster {
    seed-nodes = [
      "akka.tcp://"${clustering.cluster.name}"@"${clustering.masternode}":"${clustering.masterport}
      //"akka.tcp://"${clustering.name}"@"${clustering.ip}":"${clustering.masterport}
      //"akka.tcp://"${clustering.cluster.name}"@"${clustering.ip}":2552"
    ]
    log-info = on
    auto-down-unreachable-after = 10s
    extensions = ["akka.cluster.ddata.DistributedData"]
  }

  actor.warn-about-java-serializer-usage = false

  serializers {
    java = "akka.serialization.JavaSerializer"
  }
  // Persistance Configuration
  persistence.journal.plugin = "akka.persistence.journal.leveldb"
  persistence.snapshot-store.plugin = "akka.persistence.snapshot-store.local"

  persistence.journal.leveldb.dir = "target/jtrack/journal"
  persistence.snapshot-store.local.dir = "target/jtrack/snapshots"
  // DO NOT USE THIS IN PRODUCTION
  persistence.journal.leveldb.native = false

}


slick-ignite {
  profile = "slick.jdbc.MySQLProfile$"
  db {
    connectionPool = disabled
    dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
    properties = {
      driver = "org.apache.ignite.IgniteJdbcThinDriver"
      url = "jdbc:ignite:thin://localhost"
    }
  }
}


jtrack
  {
    database{
        host = "172.105.40.104",
        username = "jsinfo",
        password = "Mitron@123"
    }
    redis {
      host = "172.105.40.104"
      port = 6379
      password = ""
      database = 0
      timeout = 2000
      pool {
        maxTotal = 8
        maxIdle = 8
        minIdle = 0
      }
    }
    kafka {
      consumer
        {
          jtrack {
            server = "172.105.43.184:9092"
            consumerGroup="jtrackGroup",
            topic="my-topic_v2",
            offset_reset="latest",
            clientId="clientFinl",
            throttleLimit=1500,
            throttleTimeInMinutes=1
          }

          producer_jtrack{
            server = "172.105.43.184:9092"
            consumerGroup="closerGroup"
            topic="close_gate_v2"
          }
          log_topic{
            topic="jtrack.events"
          }

          cluster{
            duration = 300
            shardId = 2
          }
        }}

    cluster{
      duration = 300
      shardId = 2
    }


  }

