cube-name = jio.rtrs.jfs_pigeon_finlr_join.jfs_crawler_finlr

cube-version = "1.0"

squbs-actors = [
  {
    class-name = com.jtrack.cluster.J_InitCluster
    name = J_ClusterInit
  }
  {
    class-name = com.jtrack.kafka.KafkaJConsumer
    name = J_Consumer
  },
  {
    class-name = com.jtrack.kafka.KafkaJ_Producer
    name = J_Producer
    message-class = [
      {
        request = com.jtrack.pojo.J_Message
      }
    ]
  },
  {
  class-name = com.jtrack.cluster.CaptureDeadLetter
  name = DeadLetterCapture
    message-class = [
      {
        request = akka.actor.DeadLetter
      }
      ]
  }
]


